### ISSUE TITLE
xbmcvfs.translatePath check if path exists

### ISSUE THREAD

**Issue by mac12m99** [retrospect-addon/kodi.emulator.ascii#30]
Hi,
i see that this function check for path existence, but kodi returns no error when dealing with non-exitent paths
https://github.com/retrospect-addon/kodi.emulator.ascii/blob/037e4d0f4c7282153daa856622c14ae45aeeadd5/xbmcvfs.py#L359

But that seems intentional, there are reasons for this?

Thanks

**Comment by basrieter** [comment]
Well, it seemed like a good thing to do at the time :) But indeed, it is not 100% as Kodi does it. Is it causing you problems?

**Comment by mac12m99** [comment]
:D
Yes, but i can comment a line as a workaround, it's not a big problem, just reporting :)
However, i think that the 2 lines should and can be safely deleted.

**Comment by basrieter** [comment]
Yep, let me look into this. Perhaps I can make it a toggle somehow.

**Comment by basrieter** [comment]
I just pushed version 0.1.0 to PyPi, with these lines removed. Thanks for reporting it and let me know if you find more issues or have have suggestions.

**Comment by mac12m99** [comment]
Welcome,
of course!

And thank you for this useful module
