### ISSUE TITLE
Implement global settings

### ISSUE THREAD

**Issue by michaelarnauts** [retrospect-addon/kodi.emulator.ascii#9]
### Is your feature request related to a problem? Please describe

There is no way to get global settings at the moment. In my addon, I use the `Settings.GetSettingValue` RPC to get a setting, but the current mocking of the RPC's is fixed, so it doesn't use the passed parameter.

### Describe the solution you'd like

I think the best solution is to provide support to read out a `guisettings.xml` file, placed in the `userdata` folder. This is also the way how a real Kodi does this.

It would require to have some JSON RPC commands executed by Sake, and others can return fixed data.

### Additional context

It would make sense to implement `favourites.getfavourites` also like this, by reading `favourites.xml`.

**Comment by michaelarnauts** [comment]
@basrieter Do you think this is a good approach? An easier alternative could be to provide a dict with key values in a file somewhere, but the guisettings.xml has the benefit that it will work with a real KODI_HOME folder.

**Comment by basrieter** [comment]
Seems like the way to go. That is how I do it with the setttings.xml for add-ons themself. For CI purposes a custom guisettings.xml can be included.
